USE Master;

CREATE DATABASE MyDB
ON PRIMARY
(NAME = 'MyDB_Data',
FILENAME = 'f:\data\MyDB_Data.mdf',
SIZE = 10MB,
FILEGROWTH = 2MB,
MAXSIZE = UNLIMITED)
LOG ON
(NAME = 'MyDB_Log',
FILENAME = 'g:\logs\MyDB_Log.ldf',
SIZE = 2MB,
FILEGROWTH = 1MB,
MAXSIZE = UNLIMITED);
GO